services:
  redis:
    image: redis:alpine
    container_name: compose-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    container_name: compose-django-app
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    depends_on:
      - redis 

volumes:
  redis_data:
