[phases.setup]
nixPkgs = ["python311", "postgresql", "pkg-config", "libpq"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py makemigrations",
]

[start]
cmd = "python manage.py migrate && daphne -b 0.0.0.0 -p $PORT core.asgi:application" 