[phases.setup]
nixPkgs = ["python311", "postgresql", "pkg-config", "libpq"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
]

[start]
cmd = "gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT" 